ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/split/crowdai/0/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/crowdai-split-0.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/split/crowdai/30/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/crowdai-split-30.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/split/crowdai/70/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/crowdai-split-70.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/split/sherbrooke/0/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/sherbrooke-split-0.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/split/sherbrooke/30/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/sherbrooke-split-30.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/split/sherbrooke/70/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/sherbrooke-split-70.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/split/rouen/0/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/rouen-split-0.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/split/rouen/30/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/rouen-split-30.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/split/rouen/70/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/rouen-split-70.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/hybrid/crowdai/0/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/crowdai-hybrid-0.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/hybrid/crowdai/30/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/crowdai-hybrid-30.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/hybrid/crowdai/70/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/crowdai-hybrid-70.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/hybrid/sherbrooke/0/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/sherbrooke-hybrid-0.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/hybrid/sherbrooke/30/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/sherbrooke-hybrid-30.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/hybrid/sherbrooke/70/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/sherbrooke-hybrid-70.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/hybrid/rouen/0/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/rouen-hybrid-0.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/hybrid/rouen/30/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/rouen-hybrid-30.mp4
ffmpeg -framerate 2 -pattern_type glob -i "/users/ahjiang/src/YAD2K/images/hybrid/rouen/70/*.jpg" -c:v libx264 -pix_fmt yuv420p ~/Videos/bb/rouen-hybrid-70.mp4
